name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: run tests
      run: make test

  build:
    name: Build Package
    runs-on: self-hosted
    needs:
      - test
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build
      run: make build
