on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy package
    runs-on: self-hosted
    steps:
      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: login to GCP repo
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DEPLOY_KEY_FILE }}
      - name: Deploy
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: gcr.io/civic-eagle-enview-dev/statsd-http-proxy:${{ steps.get_tag.outputs.TAG }},gcr.io/civic-eagle-enview-dev/statsd-http-proxy:latest
          push: true
