on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy package
    runs-on: self-hosted
    steps:
      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: login to GCP repo
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DEPLOY_KEY_FILE }}
      - name: Deploy
        run: |
          docker buildx build . \
          --tag us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:${{ steps.get_tag.outputs.TAG }} --push && \
          docker tag us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:${{ steps.get_tag.outputs.TAG }} \
          us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:latest && \
          docker push us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:latest
