on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy package
    runs-on: self-hosted
    steps:
      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Set up docker -> gcp auth
        run: gcloud auth configure-docker -q
      - name: Deploy
        run: |
          docker buildx build . \
          --tag us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:${{ steps.get_tag.outputs.TAG }} --push && \
          docker tag us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:${{ steps.get_tag.outputs.TAG }} \
          us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:latest && \
          docker push us-docker.pkg.dev/civic-eagle-enview-dev/civiceagle/statsd-http-proxy:latest
